//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_M_User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Uspassword { get; set; }
        public Nullable<int> UsRoleId { get; set; }
    
        public virtual Tb_M_Role Tb_M_Role { get; set; }
    }
}
